CREATE TABLE speaking_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part INTEGER NOT NULL,
    topic TEXT NOT NULL,
    question_text TEXT NOT NULL,
    cue_card_points TEXT[],
    related_part2_topic TEXT,
    difficulty_level TEXT NOT NULL DEFAULT 'medium',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE practice_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id UUID NOT NULL REFERENCES users(id),
    question_id UUID NOT NULL REFERENCES speaking_questions(id),
    part INTEGER NOT NULL,
    audio_url TEXT,
    audio_duration_seconds DECIMAL,
    transcript TEXT,
    transcript_with_timestamps JSONB,
    overall_band_score DECIMAL(2,1),
    fluency_coherence_score DECIMAL(2,1),
    lexical_resource_score DECIMAL(2,1),
    grammar_accuracy_score DECIMAL(2,1),
    pronunciation_score DECIMAL(2,1),
    words_per_minute INTEGER,
    total_words INTEGER,
    filler_word_count INTEGER,
    filler_words_detail JSONB,
    pause_count INTEGER,
    long_pause_count INTEGER,
    pause_locations JSONB,
    feedback_fluency TEXT,
    feedback_vocabulary TEXT,
    feedback_grammar TEXT,
    feedback_pronunciation TEXT,
    feedback_overall TEXT,
    vocabulary_suggestions JSONB,
    grammar_corrections JSONB,
    mispronounced_words JSONB,
    model_answer TEXT,
    enhanced_model_answer JSONB,
    session_type TEXT NOT NULL DEFAULT 'PRACTICE',
    prep_time_used_seconds INTEGER,
    speaking_time_seconds INTEGER,
    completed_at TIMESTAMPTZ,
    mock_test_id UUID,
    question_number INTEGER
);

CREATE TABLE user_progress (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID UNIQUE NOT NULL REFERENCES users(id),
    avg_overall_score DECIMAL(3,2) DEFAULT 0,
    avg_fluency_score DECIMAL(3,2) DEFAULT 0,
    avg_lexical_score DECIMAL(3,2) DEFAULT 0,
    avg_grammar_score DECIMAL(3,2) DEFAULT 0,
    avg_pronunciation_score DECIMAL(3,2) DEFAULT 0,
    total_sessions INTEGER DEFAULT 0,
    total_practice_minutes INTEGER DEFAULT 0,
    current_streak_days INTEGER DEFAULT 0,
    longest_streak_days INTEGER DEFAULT 0,
    last_practice_date TIMESTAMPTZ,
    weak_areas JSONB,
    strong_areas JSONB,
    part1_avg_score DECIMAL(3,2) DEFAULT 0,
    part2_avg_score DECIMAL(3,2) DEFAULT 0,
    part3_avg_score DECIMAL(3,2) DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE mock_tests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id UUID NOT NULL REFERENCES users(id),
    timing_mode TEXT NOT NULL DEFAULT 'flexible',
    current_part INTEGER NOT NULL DEFAULT 1,
    current_question INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'in_progress',
    question_sequence JSONB,
    part2_topic TEXT,
    overall_score DECIMAL(2,1),
    cross_part_analysis JSONB,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);
